#!/bin/bash

while true; do
    if [[ $# -eq 0 ]]; then
        break
    fi
    case $1 in
        -i)
            interval=$2
            shift 2
            ;;
        -n)
            number=$2
            shift 2
            ;;
        *)
            command=$*
            shift $#
            ;;
    esac
done

for (( i=1; i<=$number; i++ )); do
    
    $command > /dev/null
    if [[ $? -eq 0 ]]; then
        echo "Succed after $i try."
        exit 0
    else 
        sleep $interval
    fi
done
echo "Test failed after $number try." 1>&2;
exit 1